SELECT
    t.ACTIVITY_DATE AS "Date",
    a.ACCOUNT_NAME AS "Company/Account",
    o.OPPORTUNITY_NAME AS "Opportunity",
    CASE WHEN LEFT(t.WHO_ID, 3) = '003' THEN c.NAME ELSE NULL END AS "Contact",
    CASE WHEN LEFT(t.WHO_ID, 3) = '00Q' THEN ld.FIRST_NAME || ' ' || ld.LAST_NAME ELSE NULL END AS "Lead",
    t.SUBJECT AS "Subject",
    u.FIRST_NAME || ' ' || u.LAST_NAME AS "Assigned",
    t.PRIORITY AS "Priority",
    t.STATUS AS "Status",
    t.TYPE AS "Task",
    t.ACCOUNT_ID AS "Account ID",
    t.TYPE AS "Activity Type",
    t.SALESLOFT_TYPE AS "SalesLoft Type",
    t.CREATED_AT AS "Created Date",
    COALESCE(c.LEAD_SOURCE, ld.LEAD_SOURCE) AS "Contact/Lead Source",
    CASE
        WHEN t.CREATED_AT::DATE BETWEEN '2025-06-01' AND '2025-08-31' THEN 'Q1-2026'
        WHEN t.CREATED_AT::DATE BETWEEN '2025-09-01' AND '2025-11-30' THEN 'Q2-2026'
        WHEN t.CREATED_AT::DATE BETWEEN '2025-12-01' AND '2026-02-28' THEN 'Q3-2026'
        WHEN t.CREATED_AT::DATE BETWEEN '2026-03-01' AND '2026-05-31' THEN 'Q4-2026'
        WHEN t.CREATED_AT::DATE BETWEEN '2026-06-01' AND '2026-08-31' THEN 'Q1-2027'
        WHEN t.CREATED_AT::DATE BETWEEN '2026-09-01' AND '2026-11-30' THEN 'Q2-2027'
        WHEN t.CREATED_AT::DATE BETWEEN '2026-12-01' AND '2027-02-28' THEN 'Q3-2027'
        WHEN t.CREATED_AT::DATE BETWEEN '2027-03-01' AND '2027-05-31' THEN 'Q4-2027'
        WHEN t.CREATED_AT::DATE BETWEEN '2027-06-01' AND '2027-08-31' THEN 'Q1-2028'
        WHEN t.CREATED_AT::DATE BETWEEN '2027-09-01' AND '2027-11-30' THEN 'Q2-2028'
        WHEN t.CREATED_AT::DATE BETWEEN '2027-12-01' AND '2028-02-28' THEN 'Q3-2028'
        WHEN t.CREATED_AT::DATE BETWEEN '2028-03-01' AND '2028-05-31' THEN 'Q4-2028'
        ELSE NULL
    END AS "Fiscal Period",
    CASE
        WHEN LEFT(t.WHO_ID, 3) = '003' AND c.NAME IS NOT NULL THEN c.NAME
        WHEN LEFT(t.WHO_ID, 3) = '00Q' THEN ld.FIRST_NAME || ' ' || ld.LAST_NAME
        ELSE NULL
    END AS "Final Lead Name",
    CASE COALESCE(c.LEAD_SOURCE, ld.LEAD_SOURCE)
        WHEN 'Affiliate' THEN 'Affiliate'
        WHEN 'Direct Traffic' THEN 'Direct Traffic'
        WHEN 'Organic Search' THEN 'Organic Search'
        WHEN 'Paid Search' THEN 'Paid Search'
        WHEN 'Paid Social Media' THEN 'Paid Social Media'
        WHEN 'Warm Outbound' THEN 'Warm Outbound'
        ELSE 'Other'
    END AS "Final Lead Source"
FROM PROD_SOURCE_DB.SALESFORCE.TASKS t
LEFT JOIN PROD_SOURCE_DB.SALESFORCE.ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN PROD_SOURCE_DB.SALESFORCE.OPPORTUNITIES o ON t.OPPORTUNITY_ID = o.OPPORTUNITY_ID
LEFT JOIN PROD_SOURCE_DB.SALESFORCE.CONTACTS c ON t.WHO_ID = c.CONTACT_ID AND LEFT(t.WHO_ID, 3) = '003'
LEFT JOIN PROD_SOURCE_DB.SALESFORCE.LEADS ld ON t.WHO_ID = ld.LEAD_ID AND LEFT(t.WHO_ID, 3) = '00Q'
LEFT JOIN PROD_SOURCE_DB.SALESFORCE.USERS u ON t.OWNER_ID = u.USER_ID
WHERE t.IS_DELETED = FALSE
  AND t.STATUS = 'Completed'
  AND t.ACTIVITY_DATE BETWEEN '2025-06-01' AND '2027-05-31'
  AND u.FIRST_NAME || ' ' || u.LAST_NAME IN ('Natasha Karlin','Ruznelly Fabre','Molly Casey','Amelia Wilson','Ryan Harris')
  AND (
      (t.TYPE IN ('Call', 'Email') AND LOWER(t.SUBJECT) NOT LIKE '%gong%' AND LOWER(t.SUBJECT) NOT LIKE '%salesloft%' AND LOWER(t.SUBJECT) NOT LIKE '%task%')
      OR (t.TYPE = 'Email')
      OR (t.TYPE = 'Call' AND LOWER(t.SUBJECT) LIKE '%gong outbound%' AND t.ACTIVITY_DATE >= '2026-06-01')
  )
ORDER BY t.ACTIVITY_DATE DESC;
